export const OUTPUT_LANGUAGE_OPTIONS = [
  { code: "ko", label: "한국어" },
  { code: "en", label: "English" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
  { code: "hi", label: "हिन्दी" },
];

export const SHOWCASE_COPY = {
  ko: {
    nav: { features: "기능", pricing: "요금제", start: "시작하기", language: "언어" },
    hero: {
      badgeLabel: "시험 직전 벼락치기용 AI",
      titlePrefix: "PDF 한 장으로 끝내는",
      titles: ["요약", "퀴즈", "암기카드", "AI 튜터", "모의고사"],
      description:
        "Zeusian.ai는 PDF 강의자료를 요약, 퀴즈, 암기카드, AI 튜터 흐름으로 바로 바꿔주는 시험 직전 공부 AI입니다.",
      secondaryAction: "기능 둘러보기",
      primaryAction: "바로 시작하기",
    },
    scroll: { line1: "한 화면에서 끝나는", accent: "업로드부터 복습까지" },
    features: {
      lead: "지금 공부 흐름에 바로 들어갈",
      accent: "핵심 기능",
      description: "노드를 클릭하면 각 기능이 어떻게 이어지는지 확인할 수 있습니다.",
      timeline: [
        { title: "핵심 요약", date: "STEP 1", content: "긴 PDF에서 핵심만 추려 빠르게 복습할 수 있게 정리합니다.", category: "요약", bullets: ["핵심 개념 자동 정리", "페이지 단위 문맥 유지", "정리본 PDF 저장"] },
        { title: "문제 생성", date: "STEP 2", content: "객관식, OX 등 시험형 문제를 자동 생성해 실전처럼 연습합니다.", category: "퀴즈", bullets: ["객관식과 OX 혼합", "문항별 해설 자동 연결", "10문항 모의 테스트 구성"] },
        { title: "암기 카드", date: "STEP 3", content: "헷갈리는 개념을 카드로 만들어 반복 학습합니다.", category: "플래시카드", bullets: ["개념 카드 자동 생성", "오답 카드 우선 배치", "학습 진도 추적"] },
        { title: "AI 튜터", date: "STEP 4", content: "학습 중 궁금한 내용을 바로 물어보고 문서 기반 답변을 받습니다.", category: "튜터", bullets: ["문서 기반 답변", "후속 질문 이어서 탐색", "비교 설명으로 이해 보강"] },
        { title: "모의고사", date: "STEP 5", content: "10문항 모의고사로 실전 대비 상태를 점검합니다.", category: "모의고사", bullets: ["10문항 자동 구성", "바로 채점과 정답 확인", "결과 PDF 저장"] },
        { title: "복습 루프", date: "STEP 6", content: "업로드부터 복습까지 끊기지 않는 학습 흐름을 한 화면에서 반복합니다.", category: "복습", bullets: ["업로드부터 복습까지 한 화면", "오답 중심 반복 학습", "시험 직전 최종 점검"] },
      ],
    },
    pricing: {
      lead: "필요한 만큼 시작하고",
      accent: "학습 범위에 맞게 확장하세요",
      description: "무료로 가볍게 시작하고, 더 자주 공부하면 프로로, 함께 쓰면 패밀리로 자연스럽게 넘어가면 됩니다.",
      current: "현재 선택",
      compare: "비교 항목",
      plans: [
        {
          id: "free",
          name: "무료",
          price: "무료",
          description: "가볍게 시작하는 기본 플랜",
          features: ["PDF 업로드 4개 제한", "파일별 요약/퀴즈/OX/카드 1회", "기본 학습 흐름 체험"],
          ctaLabel: "무료 시작",
        },
        {
          id: "pro",
          name: "프로",
          originalPrices: ["9,900원", "6,900원"],
          price: "0원",
          description: "혼자 꾸준히 공부하는 사용자용",
          features: ["업로드 무제한", "요약/퀴즈/OX/카드 전체 제공", "AI 튜터"],
          ctaLabel: "프로 선택",
        },
        {
          id: "premium",
          name: "패밀리",
          originalPrice: "36,000원",
          price: "월 18,900원",
          description: "최대 4명 팀 학습",
          features: ["공유 스페이스로 함께 학습", "팀원별 학습 현황 확인", "패밀리 자료 관리 기능"],
          ctaLabel: "패밀리 선택",
        },
      ],
      rows: [
        { label: "이용 방식", values: { free: "무료", pro: "개인 학습", premium: "팀 학습" } },
        { label: "월 요금", values: { free: "무료", pro: "0원", premium: "18,900원 / 월" } },
        { label: "PDF 업로드", values: { free: "최대 4개", pro: "무제한 업로드", premium: "무제한 업로드" } },
        { label: "학습 도구", values: { free: "요약 / 퀴즈 / OX / 카드 (파일별 1회)", pro: "요약 / 퀴즈 / OX / 카드", premium: "전체 기능 + 팀 학습" } },
        { label: "AI 튜터", values: { free: "기본 답변 제공", pro: "문서 기반 답변", premium: "팀 문맥 포함 답변" } },
        { label: "공간 인원", values: { free: "1명", pro: "1명", premium: "최대 4명" } },
        { label: "자료 내보내기", values: { free: "불가", pro: "PDF 저장", premium: "PDF 저장" } },
      ],
    },
    cta: {
      lead: "이제 공부 루프를",
      accent: "실제로 돌려보세요",
      description: "PDF 업로드부터 복습 문제까지, 학습 흐름 전체를 한 곳에서 정리할 준비가 되어 있습니다.",
      primary: "Zeusian.ai 시작하기",
      secondary: "지금 바로 문서 올리기",
    },
    footer: {
      titleLine1: "PDF 한 장에서",
      titleLine2: "복습 루프까지",
      description: "Zeusian.ai(제우시안 AI)는 PDF 요약, 퀴즈, 카드, AI 튜터 흐름을 한곳에서 이어줍니다.",
      companyLabel: "상호",
      legal: "법률",
      groups: [
        {
          title: "서비스",
          links: [
            { label: "기능", href: "#features" },
            { label: "요금제", href: "#pricing" },
            { label: "시작하기", href: "#cta" },
          ],
        },
        {
          title: "회사",
          links: [
            { label: "Zeusian 소개", href: "#" },
            { label: "Study AI", href: "/study-ai" },
            { label: "시작하기", href: "/start" },
          ],
        },
        {
          title: "리소스",
          links: [
            { label: "요약", href: "#features" },
            { label: "퀴즈", href: "#features" },
            { label: "카드", href: "#features" },
          ],
        },
      ],
    },
  },
  en: {
    nav: { features: "Features", pricing: "Pricing", start: "Get Started", language: "Language" },
    hero: {
      badgeLabel: "Last-minute exam prep AI",
      titlePrefix: "One PDF, ready as",
      titles: ["Summary", "Quiz", "Flashcards", "AI Tutor", "Mock Exam"],
      description:
        "Zeusian.ai turns your PDF lecture notes into summaries, quizzes, flashcards, and AI tutoring — everything you need right before the exam.",
      secondaryAction: "Explore Features",
      primaryAction: "Get Started",
    },
    scroll: { line1: "From upload to review", accent: "all in one screen" },
    features: {
      lead: "Core features built",
      accent: "into your study flow",
      description: "Click a node to see how each feature connects.",
      timeline: [
        { title: "Core Summary", date: "STEP 1", content: "Pull out only the essential points from long PDFs so you can review faster.", category: "Summary", bullets: ["Auto-organized key concepts", "Page-by-page context", "Summary PDF export"] },
        { title: "Quiz Generation", date: "STEP 2", content: "Create multiple-choice and OX questions automatically for exam-style practice.", category: "Quiz", bullets: ["Mixed question types", "Automatic explanations", "10-question mock set"] },
        { title: "Flashcards", date: "STEP 3", content: "Turn confusing concepts into cards for repeated memorization.", category: "Flashcards", bullets: ["Auto-generated concept cards", "Mistake-first review", "Study progress tracking"] },
        { title: "AI Tutor", date: "STEP 4", content: "Ask questions while studying and get answers grounded in your document.", category: "Tutor", bullets: ["Document-grounded answers", "Follow-up question flow", "Comparison-based explanations"] },
        { title: "Mock Exam", date: "STEP 5", content: "Check your readiness with a 10-question mock exam before the real test.", category: "Mock Exam", bullets: ["Auto-built 10-question set", "Instant grading and answers", "Result PDF export"] },
        { title: "Review Loop", date: "STEP 6", content: "Keep the loop from upload to review running on one screen.", category: "Review", bullets: ["Upload to review in one screen", "Mistake-focused repetition", "Final check before exam day"] },
      ],
    },
    pricing: {
      lead: "Start small",
      accent: "and scale with your workload",
      description: "Begin for free, move to Pro when you study more often, or Family when you need a shared study space.",
      current: "Current",
      compare: "Compare",
      plans: [
        {
          id: "free",
          name: "Free",
          price: "Free",
          description: "Light personal study",
          features: ["Upload up to 4 PDFs", "1 summary / quiz / OX / flashcard generation per file", "Starter storage included"],
          ctaLabel: "Choose Free",
        },
        {
          id: "pro",
          name: "Pro",
          originalPrices: ["KRW 9,900 / month", "KRW 6,900 / month"],
          price: "KRW 0",
          description: "Recommended for steady solo study",
          features: ["Unlimited uploads", "Unlimited summary / quiz / OX / cards", "Priority processing"],
          ctaLabel: "Choose Pro",
        },
        {
          id: "premium",
          name: "Family",
          originalPrice: "KRW 36,000 / month",
          price: "KRW 18,900 / month",
          description: "Shared study for up to 4 people",
          features: ["Collaborative shared space", "Separate flow for each member", "Better study efficiency together"],
          ctaLabel: "Choose Family",
        },
      ],
      rows: [
        { label: "Best for", values: { free: "Getting started", pro: "Solo study", premium: "Shared study" } },
        { label: "Monthly price", values: { free: "Free", pro: "KRW 0", premium: "KRW 18,900 / month" } },
        { label: "PDF upload", values: { free: "Up to 4 files", pro: "Unlimited", premium: "Unlimited" } },
        { label: "Core tools", values: { free: "Summary / quiz / OX / cards (1x per file)", pro: "Summary / quiz / OX / cards", premium: "Everything in Pro + shared learning" } },
        { label: "Workspace", values: { free: "Starter storage", pro: "Personal study space", premium: "Shared workspace" } },
        { label: "Users", values: { free: "1 user", pro: "1 user", premium: "Up to 4 users" } },
        { label: "Priority", values: { free: "Standard", pro: "Priority", premium: "Priority" } },
      ],
    },
    cta: {
      lead: "Put your study loop",
      accent: "into motion",
      description: "From PDF upload to final review drills, Zeusian.ai keeps the entire learning flow in one place.",
      primary: "Start Zeusian.ai",
      secondary: "Upload a Document Now",
    },
    footer: {
      titleLine1: "From one PDF",
      titleLine2: "to the full review loop",
      description: "Zeusian.ai keeps summary, quiz, flashcards, and AI tutor workflows connected in one place.",
      companyLabel: "Operator",
      legal: "Legal",
      groups: [
        {
          title: "Product",
          links: [
            { label: "Features", href: "#features" },
            { label: "Pricing", href: "#pricing" },
            { label: "Get Started", href: "#cta" },
          ],
        },
        {
          title: "Company",
          links: [
            { label: "About Zeusian", href: "#" },
            { label: "Study AI", href: "/study-ai" },
            { label: "Get Started", href: "/start" },
          ],
        },
        {
          title: "Resources",
          links: [
            { label: "Summary", href: "#features" },
            { label: "Quiz", href: "#features" },
            { label: "Flashcards", href: "#features" },
          ],
        },
      ],
    },
  },
  zh: {
    nav: { features: "功能", pricing: "价格", start: "开始使用", language: "语言" },
    hero: {
      badgeLabel: "考前冲刺 AI",
      titlePrefix: "一份 PDF 搞定",
      titles: ["摘要", "测验", "记忆卡片", "AI 导师", "模拟考试"],
      description:
        "Zeusian.ai 把 PDF 课程资料直接转换成摘要、测验、记忆卡片和 AI 导师，是考前冲刺的学习 AI。",
      secondaryAction: "浏览功能",
      primaryAction: "立即开始",
    },
    scroll: { line1: "从上传到复习", accent: "一屏完成" },
    features: {
      lead: "可直接融入",
      accent: "学习流程的核心功能",
      description: "点击节点即可查看各功能之间的关联。",
      timeline: [
        { title: "核心摘要", date: "STEP 1", content: "从长篇 PDF 中提取重点，帮助你更快进入复习状态。", category: "摘要", bullets: ["自动整理核心概念", "保留分页语境", "支持导出摘要 PDF"] },
        { title: "题目生成", date: "STEP 2", content: "自动生成选择题与 OX 判断题，直接按考试形式练习。", category: "测验", bullets: ["选择题与 OX 混合", "自动附带解析", "10 题模拟测试"] },
        { title: "记忆卡片", date: "STEP 3", content: "把容易混淆的概念做成卡片，反复记忆更高效。", category: "记忆卡片", bullets: ["自动生成概念卡", "优先复习错题卡", "跟踪学习进度"] },
        { title: "AI 导师", date: "STEP 4", content: "学习过程中随时提问，并获得基于文档内容的回答。", category: "导师", bullets: ["基于文档的回答", "支持追问延展", "对比式讲解帮助理解"] },
        { title: "模拟考试", date: "STEP 5", content: "通过 10 题模拟考试快速检查考前状态。", category: "模拟考试", bullets: ["自动生成 10 题", "即时评分与答案查看", "支持导出结果 PDF"] },
        { title: "复习闭环", date: "STEP 6", content: "从上传到复习的学习流程在同一屏幕中循环。", category: "复习", bullets: ["从上传到复习同屏完成", "以错题为中心反复练习", "考前最终检查"] },
      ],
    },
    pricing: {
      lead: "按需开始",
      accent: "随学习规模扩展",
      description: "可以先免费开始，学习更频繁时升级到 Pro，需要共享学习空间时再选择 Family。",
      current: "当前选择",
      compare: "对比项目",
      plans: [
        {
          id: "free",
          name: "免费",
          price: "免费",
          description: "适合轻量起步",
          features: ["最多上传 4 个 PDF", "提供部分摘要 / 测验 / OX 功能", "体验基础学习流程"],
          ctaLabel: "免费开始",
        },
        {
          id: "pro",
          name: "Pro",
          originalPrices: ["KRW 9,900 / month", "KRW 6,900 / month"],
          price: "KRW 0",
          description: "适合稳定的个人学习",
          features: ["无限上传", "完整提供摘要 / 测验 / OX / 卡片", "AI 导师"],
          ctaLabel: "选择 Pro",
        },
        {
          id: "premium",
          name: "Family",
          originalPrice: "₩36,000 / 月",
          price: "₩18,900 / 月",
          description: "最多 4 人共享学习",
          features: ["共享学习空间协作", "查看成员学习进度", "高级资料管理功能"],
          ctaLabel: "选择 Family",
        },
      ],
      rows: [
        { label: "适合对象", values: { free: "起步使用", pro: "个人学习", premium: "共享学习" } },
        { label: "月费", values: { free: "免费", pro: "KRW 0", premium: "KRW 18,900 / month" } },
        { label: "PDF 上传", values: { free: "最多 4 个", pro: "无限上传", premium: "无限上传" } },
        { label: "学习工具", values: { free: "部分摘要 / 测验 / OX", pro: "摘要 / 测验 / OX / 卡片", premium: "全部功能 + 团队学习" } },
        { label: "AI 导师", values: { free: "基础回答", pro: "文档依据回答", premium: "含团队上下文回答" } },
        { label: "空间人数", values: { free: "1 人", pro: "1 人", premium: "最多 4 人" } },
        { label: "资料导出", values: { free: "不可用", pro: "PDF 导出", premium: "PDF 导出" } },
      ],
    },
    cta: {
      lead: "现在就把学习闭环",
      accent: "真正跑起来",
      description: "从 PDF 上传到考前复习，Zeusian.ai 已经准备好把完整学习流程整合到一个地方。",
      primary: "开始使用 Zeusian.ai",
      secondary: "立即上传文档",
    },
    footer: {
      titleLine1: "从一份 PDF",
      titleLine2: "到完整复习闭环",
      description: "Zeusian.ai 把 PDF 摘要、测验、卡片和 AI 导师流程连接在同一个地方。",
      companyLabel: "运营方",
      legal: "法律",
      groups: [
        {
          title: "服务",
          links: [
            { label: "功能", href: "#features" },
            { label: "价格", href: "#pricing" },
            { label: "开始使用", href: "#cta" },
          ],
        },
        {
          title: "公司",
          links: [
            { label: "关于 Zeusian", href: "#" },
            { label: "Study AI", href: "/study-ai" },
            { label: "开始使用", href: "/start" },
          ],
        },
        {
          title: "资源",
          links: [
            { label: "摘要", href: "#features" },
            { label: "测验", href: "#features" },
            { label: "卡片", href: "#features" },
          ],
        },
      ],
    },
  },
  ja: {
    nav: { features: "機能", pricing: "料金", start: "始める", language: "言語" },
    hero: {
      badgeLabel: "試験直前の追い込みAI",
      titlePrefix: "PDF1枚で完結する",
      titles: ["要約", "クイズ", "暗記カード", "AIチューター", "模擬試験"],
      description:
        "Zeusian.aiはPDF講義資料を要約・クイズ・暗記カード・AIチューターの流れに変換する、試験直前用の学習AIです。",
      secondaryAction: "機能を見る",
      primaryAction: "今すぐ始める",
    },
    scroll: { line1: "アップロードから復習まで", accent: "ひとつの画面で完結" },
    features: {
      lead: "学習フローにそのまま入る",
      accent: "コア機能",
      description: "ノードをクリックすると各機能のつながりを確認できます。",
      timeline: [
        { title: "要点要約", date: "STEP 1", content: "長いPDFから本当に必要な内容だけを抜き出し、素早く復習できます。", category: "要約", bullets: ["重要概念を自動整理", "ページ単位の文脈を維持", "要約PDFを書き出し"] },
        { title: "問題生成", date: "STEP 2", content: "選択式やOX問題を自動生成し、本番形式で練習できます。", category: "クイズ", bullets: ["選択式とOXを混合", "解説を自動で接続", "10問の模擬セット"] },
        { title: "暗記カード", date: "STEP 3", content: "曖昧な概念をカード化し、反復学習しやすくします。", category: "暗記カード", bullets: ["概念カードを自動生成", "誤答カードを優先表示", "学習進捗を追跡"] },
        { title: "AIチューター", date: "STEP 4", content: "学習中に気になる点をすぐ質問し、文書ベースの回答を受け取れます。", category: "チューター", bullets: ["文書ベースの回答", "追質問をそのまま継続", "比較説明で理解を補強"] },
        { title: "模擬試験", date: "STEP 5", content: "10問の模擬試験で本番前の状態を素早く確認できます。", category: "模擬試験", bullets: ["10問を自動構成", "即時採点と正答確認", "結果PDFを書き出し"] },
        { title: "復習ループ", date: "STEP 6", content: "アップロードから復習までの流れを同じ画面で繰り返します。", category: "復習", bullets: ["アップロードから復習まで一画面", "誤答中心の反復学習", "試験直前の最終チェック"] },
      ],
    },
    pricing: {
      lead: "必要な分だけ始めて",
      accent: "学習量に合わせて広げられます",
      description: "まずは無料で始め、学習頻度が増えたらProへ、共有スペースが必要ならFamilyへ自然に移行できます。",
      current: "現在の選択",
      compare: "比較項目",
      plans: [
        {
          id: "free",
          name: "無料",
          price: "無料",
          description: "気軽に始める基本プラン",
          features: ["PDFアップロードは4件まで", "要約 / クイズ / OXの一部提供", "基本学習フローを体験"],
          ctaLabel: "無料で始める",
        },
        {
          id: "pro",
          name: "Pro",
          originalPrices: ["¥1,280 / 月", "¥980 / 月"],
          price: "¥0",
          description: "一人で継続学習する人向け",
          features: ["アップロード無制限", "要約 / クイズ / OX / カードをフル提供", "AIチューター"],
          ctaLabel: "Proを選ぶ",
        },
        {
          id: "premium",
          name: "Family",
          originalPrice: "¥2,480 / 月",
          price: "¥1,980 / 月",
          description: "最大4人の共有学習",
          features: ["共有スペースで一緒に学習", "メンバー別の進捗確認", "プレミアム資料管理機能"],
          ctaLabel: "Familyを選ぶ",
        },
      ],
      rows: [
        { label: "利用スタイル", values: { free: "はじめて使う人", pro: "個人学習", premium: "共有学習" } },
        { label: "月額", values: { free: "無料", pro: "¥980 / 月", premium: "¥1,980 / 月" } },
        { label: "PDFアップロード", values: { free: "最大4件", pro: "無制限", premium: "無制限" } },
        { label: "学習ツール", values: { free: "要約 / クイズ / OXの一部", pro: "要約 / クイズ / OX / カード", premium: "全機能 + チーム学習" } },
        { label: "AIチューター", values: { free: "基本回答", pro: "文書ベース回答", premium: "チーム文脈を含む回答" } },
        { label: "利用人数", values: { free: "1人", pro: "1人", premium: "最大4人" } },
        { label: "資料書き出し", values: { free: "不可", pro: "PDF保存", premium: "PDF保存" } },
      ],
    },
    cta: {
      lead: "学習ループを",
      accent: "実際に回してみましょう",
      description: "PDFアップロードから試験直前の復習まで、Zeusian.aiが学習フロー全体を一か所にまとめます。",
      primary: "Zeusian.aiを始める",
      secondary: "今すぐ文書をアップロード",
    },
    footer: {
      titleLine1: "1つのPDFから",
      titleLine2: "復習ループ全体へ",
      description: "Zeusian.aiはPDF要約、クイズ、カード、AIチューターの流れを一か所でつなげます。",
      companyLabel: "事業者",
      legal: "法務",
      groups: [
        {
          title: "サービス",
          links: [
            { label: "機能", href: "#features" },
            { label: "料金", href: "#pricing" },
            { label: "始める", href: "#cta" },
          ],
        },
        {
          title: "会社",
          links: [
            { label: "Zeusianについて", href: "#" },
            { label: "Study AI", href: "/study-ai" },
            { label: "始める", href: "/start" },
          ],
        },
        {
          title: "リソース",
          links: [
            { label: "要約", href: "#features" },
            { label: "クイズ", href: "#features" },
            { label: "カード", href: "#features" },
          ],
        },
      ],
    },
  },
  hi: {
    nav: { features: "फ़ीचर्स", pricing: "कीमत", start: "शुरू करें", language: "भाषा" },
    hero: {
      badgeLabel: "परीक्षा से पहले की तैयारी वाला AI",
      titlePrefix: "एक PDF से तैयार",
      titles: ["सारांश", "क्विज़", "फ़्लैशकार्ड", "AI ट्यूटर", "मॉक एग्ज़ाम"],
      description:
        "Zeusian.ai आपकी PDF लेक्चर सामग्री को सारांश, क्विज़, फ़्लैशकार्ड और AI ट्यूटर में बदल देता है — परीक्षा से ठीक पहले की पढ़ाई के लिए।",
      secondaryAction: "फ़ीचर्स देखें",
      primaryAction: "अभी शुरू करें",
    },
    scroll: { line1: "अपलोड से रिव्यू तक", accent: "सब एक ही स्क्रीन पर" },
    features: {
      lead: "आपके अध्ययन प्रवाह में सीधे जुड़ने वाले",
      accent: "मुख्य फ़ीचर्स",
      description: "किसी नोड पर क्लिक करें और देखें कि फ़ीचर्स कैसे जुड़े हैं।",
      timeline: [
        { title: "मुख्य सारांश", date: "STEP 1", content: "लंबी PDF से सिर्फ ज़रूरी बिंदु निकालकर तेज़ रिव्यू के लिए तैयार करता है।", category: "सारांश", bullets: ["मुख्य अवधारणाओं का स्वतः संगठन", "पेज-स्तर का संदर्भ बरकरार", "सारांश PDF निर्यात"] },
        { title: "क्विज़ निर्माण", date: "STEP 2", content: "मल्टीपल चॉइस और OX जैसे परीक्षा-शैली प्रश्न अपने आप बनाता है।", category: "क्विज़", bullets: ["मिश्रित प्रश्न प्रकार", "स्वचालित व्याख्या", "10-प्रश्न मॉक सेट"] },
        { title: "फ़्लैशकार्ड", date: "STEP 3", content: "कन्फ्यूज़ करने वाली अवधारणाओं को कार्ड में बदलकर बार-बार याद करने में मदद करता है।", category: "फ़्लैशकार्ड", bullets: ["अवधारणा कार्ड स्वतः बनते हैं", "गलतियों वाले कार्ड पहले", "अध्ययन प्रगति ट्रैकिंग"] },
        { title: "AI ट्यूटर", date: "STEP 4", content: "पढ़ाई के दौरान सवाल पूछें और दस्तावेज़-आधारित उत्तर पाएँ।", category: "ट्यूटर", bullets: ["दस्तावेज़-आधारित उत्तर", "फ़ॉलो-अप सवाल जारी रखें", "तुलनात्मक समझाइश"] },
        { title: "मॉक एग्ज़ाम", date: "STEP 5", content: "10 प्रश्नों के मॉक एग्ज़ाम से असली परीक्षा से पहले अपनी तैयारी जाँचें।", category: "मॉक एग्ज़ाम", bullets: ["10 प्रश्न स्वतः तैयार", "तुरंत ग्रेडिंग और उत्तर", "परिणाम PDF निर्यात"] },
        { title: "रिव्यू लूप", date: "STEP 6", content: "अपलोड से रिव्यू तक का प्रवाह एक ही स्क्रीन पर चलता रहता है।", category: "रिव्यू", bullets: ["अपलोड से रिव्यू तक एक स्क्रीन पर", "गलतियों पर केंद्रित दोहराव", "परीक्षा से पहले अंतिम जांच"] },
      ],
    },
    pricing: {
      lead: "जितनी ज़रूरत हो उतना शुरू करें",
      accent: "और पढ़ाई के साथ बढ़ें",
      description: "मुफ़्त में शुरू करें, ज़्यादा नियमित पढ़ाई पर Pro लें, और साझा अध्ययन स्पेस की ज़रूरत हो तो Family चुनें।",
      current: "वर्तमान चयन",
      compare: "तुलना बिंदु",
      plans: [
        {
          id: "free",
          name: "मुफ़्त",
          price: "मुफ़्त",
          description: "हल्के उपयोग से शुरुआत",
          features: ["अधिकतम 4 PDF अपलोड", "सारांश / क्विज़ / OX के कुछ टूल", "बेसिक अध्ययन प्रवाह का अनुभव"],
          ctaLabel: "मुफ़्त शुरू करें",
        },
        {
          id: "pro",
          name: "Pro",
          originalPrices: ["KRW 9,900 / month", "KRW 6,900 / month"],
          price: "KRW 0",
          description: "लगातार अकेले पढ़ने वालों के लिए",
          features: ["अनलिमिटेड अपलोड", "सारांश / क्विज़ / OX / कार्ड पूरे", "AI ट्यूटर"],
          ctaLabel: "Pro चुनें",
        },
        {
          id: "premium",
          name: "Family",
          originalPrice: "₩36,000 / माह",
          price: "₩18,900 / माह",
          description: "अधिकतम 4 लोगों के लिए साझा अध्ययन",
          features: ["शेयर्ड स्पेस में साथ पढ़ाई", "हर सदस्य की प्रगति देखें", "प्रीमियम सामग्री प्रबंधन"],
          ctaLabel: "Family चुनें",
        },
      ],
      rows: [
        { label: "उपयोग प्रकार", values: { free: "शुरुआत", pro: "व्यक्तिगत अध्ययन", premium: "साझा अध्ययन" } },
        { label: "मासिक शुल्क", values: { free: "मुफ़्त", pro: "KRW 0", premium: "KRW 18,900 / month" } },
        { label: "PDF अपलोड", values: { free: "अधिकतम 4 फ़ाइलें", pro: "अनलिमिटेड", premium: "अनलिमिटेड" } },
        { label: "मुख्य टूल", values: { free: "सारांश / क्विज़ / OX", pro: "सारांश / क्विज़ / OX / कार्ड", premium: "सभी फीचर + टीम अध्ययन" } },
        { label: "AI ट्यूटर", values: { free: "बेसिक उत्तर", pro: "दस्तावेज़-आधारित उत्तर", premium: "टीम संदर्भ सहित उत्तर" } },
        { label: "उपयोगकर्ता", values: { free: "1 उपयोगकर्ता", pro: "1 उपयोगकर्ता", premium: "अधिकतम 4 उपयोगकर्ता" } },
        { label: "निर्यात", values: { free: "उपलब्ध नहीं", pro: "PDF सेव", premium: "PDF सेव" } },
      ],
    },
    cta: {
      lead: "अब अपने अध्ययन लूप को",
      accent: "वास्तव में चलाइए",
      description: "PDF अपलोड से लेकर परीक्षा से पहले की रिव्यू ड्रिल तक, Zeusian.ai पूरे अध्ययन प्रवाह को एक जगह रखने के लिए तैयार है।",
      primary: "Zeusian.ai शुरू करें",
      secondary: "अभी दस्तावेज़ अपलोड करें",
    },
    footer: {
      titleLine1: "एक PDF से",
      titleLine2: "पूरे रिव्यू लूप तक",
      description: "Zeusian.ai सारांश, क्विज़, कार्ड और AI ट्यूटर को एक ही अध्ययन प्रवाह में जोड़ता है।",
      companyLabel: "संचालक",
      legal: "कानूनी",
      groups: [
        {
          title: "सेवा",
          links: [
            { label: "फ़ीचर्स", href: "#features" },
            { label: "कीमत", href: "#pricing" },
            { label: "शुरू करें", href: "#cta" },
          ],
        },
        {
          title: "कंपनी",
          links: [
            { label: "Zeusian के बारे में", href: "#" },
            { label: "Study AI", href: "/study-ai" },
            { label: "शुरू करें", href: "/start" },
          ],
        },
        {
          title: "संसाधन",
          links: [
            { label: "सारांश", href: "#features" },
            { label: "क्विज़", href: "#features" },
            { label: "कार्ड", href: "#features" },
          ],
        },
      ],
    },
  },
};
