const DETAIL_COPY = {
  ko: {
    tabs: {
      summary: "요약",
      quiz: "퀴즈",
      reviewNotes: "오답노트",
      mockExam: "모의고사",
      flashcards: "카드",
      tutor: "AI 튜터",
    },
    summary: {
      title: "요약",
      generate: "요약 생성",
      generating: "요약 생성 중...",
      pageSummary: "선택 페이지 요약",
      chapterRange: "챕터 범위 설정",
      export: "요약 PDF 다운로드",
      exporting: "PDF 내보내는 중...",
      pageSummaryTitle: "선택 페이지 요약",
      pageSummaryHint: (totalPages) => `예: 1-3,5,8 (총 ${totalPages}p)`,
      close: "닫기",
      pageSummaryPlaceholder: "페이지 번호 또는 범위를 입력하세요",
      pageSummaryLoading: "생성 중...",
    },
    pending: {
      fallbackDocumentName: "문서",
      status: "준비 중",
      opening: "문서를 여는 중입니다.",
      previewing: "원격 저장소에서 파일을 불러오고 미리보기를 준비하고 있습니다.",
      readySoon: "파일 준비가 끝나면 요약, 퀴즈, 오답노트 화면이 바로 표시됩니다.",
      firstLoadNotice:
        "잠시만 기다려 주세요. 첫 진입에서는 원격 저장소 다운로드 때문에 시간이 조금 걸릴 수 있습니다.",
    },
  },
  en: {
    tabs: {
      summary: "Summary",
      quiz: "Quiz",
      reviewNotes: "Review Notes",
      mockExam: "Mock Exam",
      flashcards: "Cards",
      tutor: "AI Tutor",
    },
    summary: {
      title: "Summary",
      generate: "Generate Summary",
      generating: "Generating Summary...",
      pageSummary: "Summarize Selected Pages",
      chapterRange: "Set Chapter Range",
      export: "Download Summary PDF",
      exporting: "Exporting PDF...",
      pageSummaryTitle: "Selected Page Summary",
      pageSummaryHint: (totalPages) => `Example: 1-3,5,8 (total ${totalPages}p)`,
      close: "Close",
      pageSummaryPlaceholder: "Enter page numbers or a range",
      pageSummaryLoading: "Generating...",
    },
    pending: {
      fallbackDocumentName: "Document",
      status: "Preparing",
      opening: "Opening your document.",
      previewing: "Fetching the file from remote storage and preparing the preview.",
      readySoon: "Once the file is ready, the summary, quiz, and review notes screen will appear.",
      firstLoadNotice:
        "Please wait a moment. On the first load, remote storage download can take a little longer.",
    },
  },
  zh: {
    tabs: {
      summary: "摘要",
      quiz: "测验",
      reviewNotes: "错题笔记",
      mockExam: "模拟考试",
      flashcards: "卡片",
      tutor: "AI 导师",
    },
    summary: {
      title: "摘要",
      generate: "生成摘要",
      generating: "正在生成摘要...",
      pageSummary: "指定页面摘要",
      chapterRange: "设置章节范围",
      export: "下载摘要 PDF",
      exporting: "正在导出 PDF...",
      pageSummaryTitle: "指定页面摘要",
      pageSummaryHint: (totalPages) => `例如：1-3,5,8（共 ${totalPages} 页）`,
      close: "关闭",
      pageSummaryPlaceholder: "输入页码或页码范围",
      pageSummaryLoading: "生成中...",
    },
    pending: {
      fallbackDocumentName: "文档",
      status: "准备中",
      opening: "正在打开文档。",
      previewing: "正在从远程存储加载文件并准备预览。",
      readySoon: "文件准备完成后，将立即显示摘要、测验和错题笔记界面。",
      firstLoadNotice: "请稍候。首次进入时，由于需要从远程存储下载文件，可能会稍慢一些。",
    },
  },
  ja: {
    tabs: {
      summary: "要約",
      quiz: "クイズ",
      reviewNotes: "復習ノート",
      mockExam: "模擬試験",
      flashcards: "カード",
      tutor: "AIチューター",
    },
    summary: {
      title: "要約",
      generate: "要約を生成",
      generating: "要約を生成中...",
      pageSummary: "選択ページを要約",
      chapterRange: "章の範囲を設定",
      export: "要約 PDF をダウンロード",
      exporting: "PDF を書き出し中...",
      pageSummaryTitle: "選択ページ要約",
      pageSummaryHint: (totalPages) => `例: 1-3,5,8（全 ${totalPages} ページ）`,
      close: "閉じる",
      pageSummaryPlaceholder: "ページ番号または範囲を入力してください",
      pageSummaryLoading: "生成中...",
    },
    pending: {
      fallbackDocumentName: "ドキュメント",
      status: "準備中",
      opening: "ドキュメントを開いています。",
      previewing: "リモートストレージからファイルを取得し、プレビューを準備しています。",
      readySoon: "ファイルの準備が完了すると、要約、クイズ、復習ノート画面が表示されます。",
      firstLoadNotice:
        "少々お待ちください。初回アクセスではリモートストレージからのダウンロードに少し時間がかかる場合があります。",
    },
  },
  hi: {
    tabs: {
      summary: "सारांश",
      quiz: "क्विज़",
      reviewNotes: "रिव्यू नोट्स",
      mockExam: "मॉक टेस्ट",
      flashcards: "कार्ड",
      tutor: "AI ट्यूटर",
    },
    summary: {
      title: "सारांश",
      generate: "सारांश बनाएँ",
      generating: "सारांश बनाया जा रहा है...",
      pageSummary: "चुने गए पेजों का सारांश",
      chapterRange: "अध्याय सीमा सेट करें",
      export: "सारांश PDF डाउनलोड करें",
      exporting: "PDF निर्यात हो रहा है...",
      pageSummaryTitle: "चुने गए पेजों का सारांश",
      pageSummaryHint: (totalPages) => `उदाहरण: 1-3,5,8 (कुल ${totalPages} पेज)`,
      close: "बंद करें",
      pageSummaryPlaceholder: "पेज नंबर या रेंज दर्ज करें",
      pageSummaryLoading: "बनाया जा रहा है...",
    },
    pending: {
      fallbackDocumentName: "दस्तावेज़",
      status: "तैयार हो रहा है",
      opening: "दस्तावेज़ खोला जा रहा है।",
      previewing: "रिमोट स्टोरेज से फ़ाइल लाकर प्रीव्यू तैयार किया जा रहा है।",
      readySoon: "फ़ाइल तैयार होते ही सारांश, क्विज़ और रिव्यू नोट्स स्क्रीन दिखाई देगी।",
      firstLoadNotice:
        "कृपया थोड़ी देर प्रतीक्षा करें। पहली बार खोलने पर रिमोट स्टोरेज डाउनलोड के कारण थोड़ा समय लग सकता है।",
    },
  },
};

export function getDetailCopy(outputLanguage = "ko") {
  return DETAIL_COPY[outputLanguage] ?? DETAIL_COPY.ko;
}
