const OUTPUT_LANGUAGE_OPTIONS = [
  { code: "en", label: "English" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
  { code: "hi", label: "हिन्दी" },
  { code: "ko", label: "한국어" },
];

const SETTINGS_COPY = {
  ko: {
    locale: "ko-KR",
    planNames: {
      free: "무료",
      pro: "프로",
      premium: "프리미엄",
    },
    sections: {
      account: "계정",
      subscription: "구독",
      theme: "테마",
      feedback: "개선 요청",
      language: "언어",
    },
    modal: {
      title: "설정",
      close: "닫기",
      closeAria: "설정 창 닫기",
    },
    theme: {
      dark: "다크",
      light: "라이트",
      darkDescription: "어두운 배경으로 집중하기 좋습니다.",
      lightDescription: "밝은 배경으로 문서를 보기 좋습니다.",
      current: (label) => `현재 ${label} 테마가 적용되어 있습니다.`,
    },
    common: {
      loading: "불러오는 중..",
      refresh: "새로고침",
      refreshing: "새로고침 중..",
      login: "로그인",
      logout: "로그아웃",
      loggingOut: "로그아웃 중..",
      none: "없음",
      unknown: "확인 필요",
      replied: "답장 완료",
      unreplied: "미답장",
      delete: "삭제",
      deleting: "삭제 중..",
      send: "답장 보내기",
      sending: "답장 전송 중..",
    },
    status: {
      active: "활성",
      inactive: "비활성",
      none: "없음",
    },
    feedbackCategory: {
      bug: "버그",
      feature: "기능 제안",
      ux: "사용성",
      general: "일반",
    },
    account: {
      title: "계정",
      description: "현재 로그인 상태와 연결된 계정을 확인합니다.",
      accountStatus: "계정 상태",
      currentPlan: "현재 플랜",
      email: "이메일",
      planStatus: "플랜 상태",
      activeProfile: "활성 프로필",
      noActiveProfile: "선택된 프로필 없음",
      spaceMode: "공간 모드",
      sharedSpace: "공유 스페이스",
      personalSpace: "개인 스페이스",
      loggedIn: "로그인됨",
      guest: "게스트",
      guestMode: "비회원 모드",
      guestDescription: "로그인하면 결제와 피드백을 연결할 수 있습니다.",
      guestModeDescription: "현재는 로그인을 사용하지 않는 모드입니다.",
    },
    subscription: {
      title: "구독",
      description: "현재 플랜과 결제 방식을 짧게 확인합니다.",
      loadingPlan: "확인 중..",
      loadingStatus: "요금제 상태를 불러오는 중입니다.",
      freePlan: "무료 플랜",
      daysRemaining: (days) => `${days}일 남음`,
      expiresOn: (value) => `만료 ${value}`,
      expiryUnknown: "만료일 확인 필요",
      multipleRecurring: "복수 정기결제",
      multipleRecurringDescription: "카카오페이와 카드 정기결제가 모두 활성입니다.",
      cardRecurring: "카드 정기결제",
      cardRecurringActive: "카드 자동결제 활성",
      kakaoRecurring: "카카오페이 정기결제",
      kakaoRecurringActive: "카카오페이 자동결제 활성",
      nextPaymentInline: (value) => `다음 결제 ${value}`,
      unsubscribed: "미구독",
      freePlanDescription: "현재 Free 플랜 이용 중입니다.",
      noSubscription: "구독 없음",
      withoutRecurring: "활성 정기결제 없이 이용 중입니다.",
      paymentMethodUnknown: "결제 수단을 아직 확인하지 못했습니다.",
      subscriptionMethod: "구독 방식",
      expiryOrNextPayment: "만료/다음 결제",
      detailMemo: "상세 메모",
      openBilling: "요금제 열기",
      refreshSubscription: "구독 새로고침",
      cancelPlan: "플랜 취소",
      cancellingPlan: "플랜 취소 중..",
      kakaoPay: "카카오페이",
      cardPayment: "카드 결제",
      status: "상태",
      plan: "요금제",
      billingCycle: "결제 주기",
      paymentMethod: "결제 수단",
      nextPayment: "다음 결제",
      months: (months) => `${months}개월`,
      cancelNeedsSession: "구독을 취소하려면 로그인 세션이 필요합니다.",
      cancelProviderFallback: "구독",
      cancelFailed: "취소에 실패했습니다.",
      cancelledNotice: (providers) =>
        `${providers.join(", ")} 정기결제를 해지했습니다. 현재 이용 기간은 만료일까지 유지됩니다.`,
      partialCancelled: (message) => `일부 구독만 해지되었습니다. ${message}`,
      planCancelFailed: "플랜 취소에 실패했습니다.",
      loadFailed: "구독 상태를 불러오지 못했습니다.",
      niceCardLabel: "나이스페이먼츠 카드",
    },
    language: {
      title: "언어",
      description: "",
      current: (label) => `현재 ${label}가 요약, 퀴즈, O/X, 카드, AI 튜터, 시험 직전 정리에 공통 적용됩니다.`,
    },
    feedback: {
      title: "개선 요청",
      description: "불편한 점이나 제안을 바로 남깁니다.",
      introTitle: "서비스 개선에 도움을 주세요.",
      introDescription:
        "버그, 제안, 불편한 점을 짧게 남겨주시면 됩니다. 어떤 화면에서 막혔는지 적어주시면 바로 확인하기 좋습니다.",
      introDisabled: "현재 모드에서는 피드백 기능이 연결되어 있지 않습니다.",
      leaveFeedback: "피드백 남기기",
      repliesTitle: "답장",
      repliesDescription: "운영자가 보낸 답장이 오면 여기에서 확인할 수 있습니다.",
      repliesLoading: "답장을 불러오는 중입니다.",
      adminReply: "운영자 답장",
      myFeedback: "내가 보낸 피드백",
      noReplies: "아직 받은 답장이 없습니다.",
      managementTitle: "피드백 관리",
      managementDescription: "제출자의 정보와 문맥을 보고 바로 답장 메일을 보낼 수 있습니다.",
      inboxLoading: "피드백 목록을 불러오는 중입니다.",
      noRecentFeedback: "최근 피드백이 없습니다.",
      noEmail: "이메일 없음",
      recentReply: (value) => `최근 답장 ${value}`,
      replyPlaceholder: "이 피드백에 답장할 내용을 입력하세요.",
      deleteConfirm: "이 답장을 삭제할까요?",
      replyDraftRequired: "답장 내용을 입력해 주세요.",
      replyNeedsSession: "답장을 보내려면 로그인 세션이 필요합니다.",
      replySent: "답장을 전송했습니다.",
      replySendFailed: "답장 전송에 실패했습니다.",
      replyLoadFailed: "답장을 불러오지 못했습니다.",
      replyDeleteNeedsSession: "답장을 삭제하려면 로그인 세션이 필요합니다.",
      replyDeleteFailed: "답장을 삭제하지 못했습니다.",
      inboxLoadFailed: "피드백 목록을 불러오지 못했습니다.",
    },
  },
  en: {
    locale: "en-US",
    planNames: {
      free: "Free",
      pro: "Pro",
      premium: "Premium",
    },
    sections: {
      account: "Account",
      subscription: "Subscription",
      theme: "Theme",
      feedback: "Feedback",
      language: "Language",
    },
    modal: {
      title: "Settings",
      close: "Close",
      closeAria: "Close settings",
    },
    theme: {
      dark: "Dark",
      light: "Light",
      darkDescription: "Best when you want a darker, more focused workspace.",
      lightDescription: "Best when you want a brighter document view.",
      current: (label) => `The ${label} theme is currently applied.`,
    },
    common: {
      loading: "Loading..",
      refresh: "Refresh",
      refreshing: "Refreshing..",
      login: "Log In",
      logout: "Log Out",
      loggingOut: "Logging out..",
      none: "None",
      unknown: "Needs review",
      replied: "Replied",
      unreplied: "Pending",
      delete: "Delete",
      deleting: "Deleting..",
      send: "Send Reply",
      sending: "Sending..",
    },
    status: {
      active: "Active",
      inactive: "Inactive",
      none: "None",
    },
    feedbackCategory: {
      bug: "Bug",
      feature: "Feature",
      ux: "Usability",
      general: "General",
    },
    account: {
      title: "Account",
      description: "Check your current sign-in state and linked account.",
      accountStatus: "Account status",
      currentPlan: "Current plan",
      email: "Email",
      planStatus: "Plan status",
      activeProfile: "Active profile",
      noActiveProfile: "No profile selected",
      spaceMode: "Space mode",
      sharedSpace: "Shared space",
      personalSpace: "Personal space",
      loggedIn: "Signed in",
      guest: "Guest",
      guestMode: "No-auth mode",
      guestDescription: "Sign in to connect billing and feedback.",
      guestModeDescription: "This mode is currently running without sign-in.",
    },
    subscription: {
      title: "Subscription",
      description: "Review your current plan and payment method at a glance.",
      loadingPlan: "Checking..",
      loadingStatus: "Loading your plan status.",
      freePlan: "Free plan",
      daysRemaining: (days) => `${days} days left`,
      expiresOn: (value) => `Expires ${value}`,
      expiryUnknown: "Expiration date unavailable",
      multipleRecurring: "Multiple subscriptions",
      multipleRecurringDescription: "KakaoPay and card billing are both active.",
      cardRecurring: "Card subscription",
      cardRecurringActive: "Card auto-renew is active",
      kakaoRecurring: "KakaoPay subscription",
      kakaoRecurringActive: "KakaoPay auto-renew is active",
      nextPaymentInline: (value) => `Next payment ${value}`,
      unsubscribed: "No subscription",
      freePlanDescription: "You are currently using the Free plan.",
      noSubscription: "No active subscription",
      withoutRecurring: "Using the service without active recurring billing.",
      paymentMethodUnknown: "Payment method has not been verified yet.",
      subscriptionMethod: "Subscription method",
      expiryOrNextPayment: "Expiry / Next payment",
      detailMemo: "Details",
      openBilling: "Open Pricing",
      refreshSubscription: "Refresh subscription",
      cancelPlan: "Cancel plan",
      cancellingPlan: "Cancelling..",
      kakaoPay: "KakaoPay",
      cardPayment: "Card payment",
      status: "Status",
      plan: "Plan",
      billingCycle: "Billing cycle",
      paymentMethod: "Payment method",
      nextPayment: "Next payment",
      months: (months) => `${months} month${Number(months) === 1 ? "" : "s"}`,
      cancelNeedsSession: "You need an active session to cancel the subscription.",
      cancelProviderFallback: "Subscription",
      cancelFailed: "Cancellation failed.",
      cancelledNotice: (providers) =>
        `${providers.join(", ")} subscription billing was cancelled. Your current access stays active until the end date.`,
      partialCancelled: (message) => `Only part of the subscriptions were cancelled. ${message}`,
      planCancelFailed: "Failed to cancel the plan.",
      loadFailed: "Failed to load subscription status.",
      niceCardLabel: "NICE Payments card",
    },
    language: {
      title: "Language",
      description: "",
      current: (label) =>
        `${label} now applies across summaries, quizzes, O/X, flashcards, AI tutor, and exam cram notes.`,
    },
    feedback: {
      title: "Feedback",
      description: "Send suggestions or report rough edges right away.",
      introTitle: "Help improve the service.",
      introDescription:
        "You can leave a short bug report, suggestion, or pain point. It is especially helpful if you mention which screen blocked you.",
      introDisabled: "Feedback is not connected in the current mode.",
      leaveFeedback: "Leave feedback",
      repliesTitle: "Replies",
      repliesDescription: "Any reply from the team will appear here.",
      repliesLoading: "Loading replies.",
      adminReply: "Team reply",
      myFeedback: "My feedback",
      noReplies: "No replies yet.",
      managementTitle: "Feedback management",
      managementDescription: "See sender context and send a reply email directly.",
      inboxLoading: "Loading feedback list.",
      noRecentFeedback: "No recent feedback.",
      noEmail: "No email",
      recentReply: (value) => `Recent reply ${value}`,
      replyPlaceholder: "Write a reply to this feedback.",
      deleteConfirm: "Delete this reply?",
      replyDraftRequired: "Please enter a reply.",
      replyNeedsSession: "You need an active session to send a reply.",
      replySent: "Reply sent.",
      replySendFailed: "Failed to send reply.",
      replyLoadFailed: "Failed to load replies.",
      replyDeleteNeedsSession: "You need an active session to delete a reply.",
      replyDeleteFailed: "Failed to delete reply.",
      inboxLoadFailed: "Failed to load feedback list.",
    },
  },
  zh: {
    locale: "zh-CN",
    planNames: {
      free: "免费",
      pro: "Pro",
      premium: "Premium",
    },
    sections: {
      account: "账户",
      subscription: "订阅",
      theme: "主题",
      feedback: "反馈",
      language: "语言",
    },
    modal: {
      title: "设置",
      close: "关闭",
      closeAria: "关闭设置",
    },
    theme: {
      dark: "深色",
      light: "浅色",
      darkDescription: "适合在深色背景下更专注地学习。",
      lightDescription: "适合在明亮背景下查看文档。",
      current: (label) => `当前正在使用 ${label} 主题。`,
    },
    common: {
      loading: "加载中..",
      refresh: "刷新",
      refreshing: "刷新中..",
      login: "登录",
      logout: "退出登录",
      loggingOut: "退出中..",
      none: "无",
      unknown: "待确认",
      replied: "已回复",
      unreplied: "未回复",
      delete: "删除",
      deleting: "删除中..",
      send: "发送回复",
      sending: "发送中..",
    },
    status: {
      active: "启用",
      inactive: "未启用",
      none: "无",
    },
    feedbackCategory: {
      bug: "Bug",
      feature: "功能建议",
      ux: "易用性",
      general: "一般",
    },
    account: {
      title: "账户",
      description: "查看当前登录状态和关联账户信息。",
      accountStatus: "账户状态",
      currentPlan: "当前方案",
      email: "邮箱",
      planStatus: "方案状态",
      activeProfile: "当前档案",
      noActiveProfile: "未选择档案",
      spaceMode: "空间模式",
      sharedSpace: "共享空间",
      personalSpace: "个人空间",
      loggedIn: "已登录",
      guest: "访客",
      guestMode: "无登录模式",
      guestDescription: "登录后即可关联支付和反馈。",
      guestModeDescription: "当前模式未启用登录。",
    },
    subscription: {
      title: "订阅",
      description: "快速查看当前方案和支付方式。",
      loadingPlan: "确认中..",
      loadingStatus: "正在加载方案状态。",
      freePlan: "免费方案",
      daysRemaining: (days) => `剩余 ${days} 天`,
      expiresOn: (value) => `到期 ${value}`,
      expiryUnknown: "无法确认到期日",
      multipleRecurring: "多个定期订阅",
      multipleRecurringDescription: "KakaoPay 与信用卡定期付款均处于启用状态。",
      cardRecurring: "信用卡订阅",
      cardRecurringActive: "信用卡自动扣费已启用",
      kakaoRecurring: "KakaoPay 订阅",
      kakaoRecurringActive: "KakaoPay 自动扣费已启用",
      nextPaymentInline: (value) => `下次付款 ${value}`,
      unsubscribed: "未订阅",
      freePlanDescription: "当前正在使用 Free 方案。",
      noSubscription: "没有有效订阅",
      withoutRecurring: "当前没有启用定期付款。",
      paymentMethodUnknown: "尚未确认支付方式。",
      subscriptionMethod: "订阅方式",
      expiryOrNextPayment: "到期 / 下次付款",
      detailMemo: "详细说明",
      openBilling: "打开价格页",
      refreshSubscription: "刷新订阅",
      cancelPlan: "取消方案",
      cancellingPlan: "取消中..",
      kakaoPay: "KakaoPay",
      cardPayment: "卡片支付",
      status: "状态",
      plan: "方案",
      billingCycle: "扣费周期",
      paymentMethod: "支付方式",
      nextPayment: "下次付款",
      months: (months) => `${months}个月`,
      cancelNeedsSession: "需要有效登录会话才能取消订阅。",
      cancelProviderFallback: "订阅",
      cancelFailed: "取消失败。",
      cancelledNotice: (providers) =>
        `已取消 ${providers.join("、")} 的定期扣费。当前使用权限会保留到到期日。`,
      partialCancelled: (message) => `仅部分订阅已取消。${message}`,
      planCancelFailed: "取消方案失败。",
      loadFailed: "无法加载订阅状态。",
      niceCardLabel: "NICE Payments 卡片",
    },
    language: {
      title: "语言",
      description: "",
      current: (label) => `当前 ${label} 会统一应用到摘要、测验、O/X、卡片、AI 导师和考前整理。`,
    },
    feedback: {
      title: "反馈",
      description: "快速提交建议或问题。",
      introTitle: "帮助我们改进服务。",
      introDescription: "你可以简短留下 Bug、建议或不便之处。如果能说明是哪一个页面卡住了，会更容易快速确认。",
      introDisabled: "当前模式下未连接反馈功能。",
      leaveFeedback: "提交反馈",
      repliesTitle: "回复",
      repliesDescription: "运营发送的回复会显示在这里。",
      repliesLoading: "正在加载回复。",
      adminReply: "运营回复",
      myFeedback: "我的反馈",
      noReplies: "还没有收到回复。",
      managementTitle: "反馈管理",
      managementDescription: "查看提交者信息和上下文，并可直接发送回复邮件。",
      inboxLoading: "正在加载反馈列表。",
      noRecentFeedback: "最近没有反馈。",
      noEmail: "无邮箱",
      recentReply: (value) => `最近回复 ${value}`,
      replyPlaceholder: "输入对此反馈的回复内容。",
      deleteConfirm: "要删除这条回复吗？",
      replyDraftRequired: "请输入回复内容。",
      replyNeedsSession: "发送回复需要有效登录会话。",
      replySent: "回复已发送。",
      replySendFailed: "发送回复失败。",
      replyLoadFailed: "无法加载回复。",
      replyDeleteNeedsSession: "删除回复需要有效登录会话。",
      replyDeleteFailed: "删除回复失败。",
      inboxLoadFailed: "无法加载反馈列表。",
    },
  },
  ja: {
    locale: "ja-JP",
    planNames: {
      free: "無料",
      pro: "Pro",
      premium: "Premium",
    },
    sections: {
      account: "アカウント",
      subscription: "サブスクリプション",
      theme: "テーマ",
      feedback: "フィードバック",
      language: "言語",
    },
    modal: {
      title: "設定",
      close: "閉じる",
      closeAria: "設定を閉じる",
    },
    theme: {
      dark: "ダーク",
      light: "ライト",
      darkDescription: "暗い背景で集中しやすい表示です。",
      lightDescription: "明るい背景で文書を見やすく表示します。",
      current: (label) => `現在は${label}テーマが適用されています。`,
    },
    common: {
      loading: "読み込み中..",
      refresh: "更新",
      refreshing: "更新中..",
      login: "ログイン",
      logout: "ログアウト",
      loggingOut: "ログアウト中..",
      none: "なし",
      unknown: "確認が必要",
      replied: "返信済み",
      unreplied: "未返信",
      delete: "削除",
      deleting: "削除中..",
      send: "返信を送信",
      sending: "送信中..",
    },
    status: {
      active: "有効",
      inactive: "無効",
      none: "なし",
    },
    feedbackCategory: {
      bug: "バグ",
      feature: "機能提案",
      ux: "使いやすさ",
      general: "一般",
    },
    account: {
      title: "アカウント",
      description: "現在のログイン状態と接続中のアカウントを確認します。",
      accountStatus: "アカウント状態",
      currentPlan: "現在のプラン",
      email: "メール",
      planStatus: "プラン状態",
      activeProfile: "有効プロフィール",
      noActiveProfile: "選択されたプロフィールはありません",
      spaceMode: "スペースモード",
      sharedSpace: "共有スペース",
      personalSpace: "個人スペース",
      loggedIn: "ログイン済み",
      guest: "ゲスト",
      guestMode: "非会員モード",
      guestDescription: "ログインすると決済とフィードバックを連携できます。",
      guestModeDescription: "現在はログインを使わないモードです。",
    },
    subscription: {
      title: "サブスクリプション",
      description: "現在のプランと決済方法をすばやく確認します。",
      loadingPlan: "確認中..",
      loadingStatus: "プラン状態を読み込み中です。",
      freePlan: "無料プラン",
      daysRemaining: (days) => `${days}日残り`,
      expiresOn: (value) => `期限 ${value}`,
      expiryUnknown: "有効期限を確認できません",
      multipleRecurring: "複数の定期決済",
      multipleRecurringDescription: "KakaoPay とカード定期決済の両方が有効です。",
      cardRecurring: "カード定期決済",
      cardRecurringActive: "カード自動決済が有効です",
      kakaoRecurring: "KakaoPay 定期決済",
      kakaoRecurringActive: "KakaoPay 自動決済が有効です",
      nextPaymentInline: (value) => `次回決済 ${value}`,
      unsubscribed: "未契約",
      freePlanDescription: "現在 Free プランを利用中です。",
      noSubscription: "契約なし",
      withoutRecurring: "有効な定期決済なしで利用中です。",
      paymentMethodUnknown: "決済手段をまだ確認できていません。",
      subscriptionMethod: "契約方式",
      expiryOrNextPayment: "期限 / 次回決済",
      detailMemo: "詳細メモ",
      openBilling: "料金ページを開く",
      refreshSubscription: "契約を更新",
      cancelPlan: "プランを解約",
      cancellingPlan: "解約中..",
      kakaoPay: "KakaoPay",
      cardPayment: "カード決済",
      status: "状態",
      plan: "プラン",
      billingCycle: "決済周期",
      paymentMethod: "決済手段",
      nextPayment: "次回決済",
      months: (months) => `${months}か月`,
      cancelNeedsSession: "解約には有効なログインセッションが必要です。",
      cancelProviderFallback: "契約",
      cancelFailed: "解約に失敗しました。",
      cancelledNotice: (providers) =>
        `${providers.join("、")}の定期決済を解約しました。現在の利用期間は満了日まで維持されます。`,
      partialCancelled: (message) => `一部の契約のみ解約されました。${message}`,
      planCancelFailed: "プラン解約に失敗しました。",
      loadFailed: "契約状態を取得できませんでした。",
      niceCardLabel: "NICE Payments カード",
    },
    language: {
      title: "言語",
      description: "",
      current: (label) =>
        `現在 ${label} が要約、クイズ、O/X、カード、AIチューター、試験直前整理に共通で適用されています。`,
    },
    feedback: {
      title: "フィードバック",
      description: "不便な点や提案をすぐに送れます。",
      introTitle: "サービス改善にご協力ください。",
      introDescription:
        "バグ、提案、不便だった点を短く残してください。どの画面で詰まったのか書いてもらえると確認しやすくなります。",
      introDisabled: "現在のモードではフィードバック機能が接続されていません。",
      leaveFeedback: "フィードバックを送る",
      repliesTitle: "返信",
      repliesDescription: "運営からの返信が届くとここで確認できます。",
      repliesLoading: "返信を読み込み中です。",
      adminReply: "運営からの返信",
      myFeedback: "自分が送ったフィードバック",
      noReplies: "まだ届いた返信はありません。",
      managementTitle: "フィードバック管理",
      managementDescription: "送信者情報と文脈を見ながらそのまま返信メールを送れます。",
      inboxLoading: "フィードバック一覧を読み込み中です。",
      noRecentFeedback: "最近のフィードバックはありません。",
      noEmail: "メールなし",
      recentReply: (value) => `最近の返信 ${value}`,
      replyPlaceholder: "このフィードバックへの返信内容を入力してください。",
      deleteConfirm: "この返信を削除しますか？",
      replyDraftRequired: "返信内容を入力してください。",
      replyNeedsSession: "返信送信には有効なログインセッションが必要です。",
      replySent: "返信を送信しました。",
      replySendFailed: "返信送信に失敗しました。",
      replyLoadFailed: "返信を読み込めませんでした。",
      replyDeleteNeedsSession: "返信削除には有効なログインセッションが必要です。",
      replyDeleteFailed: "返信を削除できませんでした。",
      inboxLoadFailed: "フィードバック一覧を読み込めませんでした。",
    },
  },
  hi: {
    locale: "hi-IN",
    planNames: {
      free: "मुफ़्त",
      pro: "Pro",
      premium: "Premium",
    },
    sections: {
      account: "खाता",
      subscription: "सब्सक्रिप्शन",
      theme: "थीम",
      feedback: "फ़ीडबैक",
      language: "भाषा",
    },
    modal: {
      title: "सेटिंग्स",
      close: "बंद करें",
      closeAria: "सेटिंग्स बंद करें",
    },
    theme: {
      dark: "डार्क",
      light: "लाइट",
      darkDescription: "गहरे बैकग्राउंड के साथ ध्यान लगाकर पढ़ने के लिए अच्छा है।",
      lightDescription: "उजले बैकग्राउंड पर दस्तावेज़ पढ़ने के लिए अच्छा है।",
      current: (label) => `अभी ${label} थीम लागू है।`,
    },
    common: {
      loading: "लोड हो रहा है..",
      refresh: "रीफ़्रेश",
      refreshing: "रीफ़्रेश हो रहा है..",
      login: "लॉग इन",
      logout: "लॉग आउट",
      loggingOut: "लॉग आउट हो रहा है..",
      none: "कोई नहीं",
      unknown: "जाँच आवश्यक",
      replied: "जवाब दिया गया",
      unreplied: "जवाब लंबित",
      delete: "हटाएँ",
      deleting: "हटाया जा रहा है..",
      send: "जवाब भेजें",
      sending: "भेजा जा रहा है..",
    },
    status: {
      active: "सक्रिय",
      inactive: "निष्क्रिय",
      none: "कोई नहीं",
    },
    feedbackCategory: {
      bug: "बग",
      feature: "फ़ीचर सुझाव",
      ux: "उपयोगिता",
      general: "सामान्य",
    },
    account: {
      title: "खाता",
      description: "अपनी वर्तमान लॉग-इन स्थिति और जुड़े खाते की जाँच करें।",
      accountStatus: "खाता स्थिति",
      currentPlan: "वर्तमान प्लान",
      email: "ईमेल",
      planStatus: "प्लान स्थिति",
      activeProfile: "सक्रिय प्रोफ़ाइल",
      noActiveProfile: "कोई प्रोफ़ाइल चयनित नहीं है",
      spaceMode: "स्पेस मोड",
      sharedSpace: "शेयर्ड स्पेस",
      personalSpace: "पर्सनल स्पेस",
      loggedIn: "लॉग इन है",
      guest: "गेस्ट",
      guestMode: "बिना लॉग-इन मोड",
      guestDescription: "लॉग इन करने पर भुगतान और फ़ीडबैक जोड़ा जा सकता है।",
      guestModeDescription: "अभी यह मोड लॉग-इन के बिना चल रहा है।",
    },
    subscription: {
      title: "सब्सक्रिप्शन",
      description: "वर्तमान प्लान और भुगतान तरीके को जल्दी से देखें।",
      loadingPlan: "जाँचा जा रहा है..",
      loadingStatus: "प्लान स्थिति लोड की जा रही है।",
      freePlan: "मुफ़्त प्लान",
      daysRemaining: (days) => `${days} दिन शेष`,
      expiresOn: (value) => `समाप्ति ${value}`,
      expiryUnknown: "समाप्ति तिथि उपलब्ध नहीं है",
      multipleRecurring: "एकाधिक आवर्ती सदस्यताएँ",
      multipleRecurringDescription: "KakaoPay और कार्ड बिलिंग दोनों सक्रिय हैं।",
      cardRecurring: "कार्ड सब्सक्रिप्शन",
      cardRecurringActive: "कार्ड ऑटो-पे सक्रिय है",
      kakaoRecurring: "KakaoPay सब्सक्रिप्शन",
      kakaoRecurringActive: "KakaoPay ऑटो-पे सक्रिय है",
      nextPaymentInline: (value) => `अगला भुगतान ${value}`,
      unsubscribed: "कोई सदस्यता नहीं",
      freePlanDescription: "आप अभी Free प्लान उपयोग कर रहे हैं।",
      noSubscription: "सक्रिय सदस्यता नहीं",
      withoutRecurring: "सक्रिय आवर्ती भुगतान के बिना उपयोग में है।",
      paymentMethodUnknown: "भुगतान विधि अभी सत्यापित नहीं हुई है।",
      subscriptionMethod: "सब्सक्रिप्शन तरीका",
      expiryOrNextPayment: "समाप्ति / अगला भुगतान",
      detailMemo: "विवरण",
      openBilling: "Pricing खोलें",
      refreshSubscription: "सब्सक्रिप्शन रीफ़्रेश करें",
      cancelPlan: "प्लान रद्द करें",
      cancellingPlan: "रद्द किया जा रहा है..",
      kakaoPay: "KakaoPay",
      cardPayment: "कार्ड भुगतान",
      status: "स्थिति",
      plan: "प्लान",
      billingCycle: "बिलिंग चक्र",
      paymentMethod: "भुगतान विधि",
      nextPayment: "अगला भुगतान",
      months: (months) => `${months} माह`,
      cancelNeedsSession: "सब्सक्रिप्शन रद्द करने के लिए सक्रिय लॉग-इन सेशन चाहिए।",
      cancelProviderFallback: "सब्सक्रिप्शन",
      cancelFailed: "रद्द करना विफल रहा।",
      cancelledNotice: (providers) =>
        `${providers.join(", ")} की आवर्ती बिलिंग रद्द कर दी गई है। आपकी वर्तमान पहुंच समाप्ति तिथि तक बनी रहेगी।`,
      partialCancelled: (message) => `केवल कुछ सदस्यताएँ रद्द हुईं। ${message}`,
      planCancelFailed: "प्लान रद्द नहीं किया जा सका।",
      loadFailed: "सब्सक्रिप्शन स्थिति लोड नहीं हो सकी।",
      niceCardLabel: "NICE Payments कार्ड",
    },
    language: {
      title: "भाषा",
      description: "",
      current: (label) =>
        `अभी ${label} सारांश, क्विज़, O/X, कार्ड, AI ट्यूटर और परीक्षा से पहले की नोट्स पर समान रूप से लागू है।`,
    },
    feedback: {
      title: "फ़ीडबैक",
      description: "सुझाव या असुविधा तुरंत साझा करें।",
      introTitle: "सेवा सुधारने में मदद करें।",
      introDescription:
        "आप छोटा बग, सुझाव या परेशानी लिख सकते हैं। किस स्क्रीन पर अटके थे, यह लिखने से जाँच करना आसान हो जाता है।",
      introDisabled: "वर्तमान मोड में फ़ीडबैक सुविधा जुड़ी हुई नहीं है।",
      leaveFeedback: "फ़ीडबैक भेजें",
      repliesTitle: "जवाब",
      repliesDescription: "टीम की ओर से आया जवाब यहाँ दिखाई देगा।",
      repliesLoading: "जवाब लोड हो रहे हैं।",
      adminReply: "टीम का जवाब",
      myFeedback: "मेरा फ़ीडबैक",
      noReplies: "अभी तक कोई जवाब नहीं मिला।",
      managementTitle: "फ़ीडबैक प्रबंधन",
      managementDescription: "प्रेषक की जानकारी और संदर्भ देखकर सीधे जवाबी ईमेल भेजें।",
      inboxLoading: "फ़ीडबैक सूची लोड हो रही है।",
      noRecentFeedback: "हाल का कोई फ़ीडबैक नहीं है।",
      noEmail: "ईमेल नहीं",
      recentReply: (value) => `हाल का जवाब ${value}`,
      replyPlaceholder: "इस फ़ीडबैक के लिए जवाब लिखें।",
      deleteConfirm: "क्या इस जवाब को हटाना है?",
      replyDraftRequired: "कृपया जवाब लिखें।",
      replyNeedsSession: "जवाब भेजने के लिए सक्रिय लॉग-इन सेशन चाहिए।",
      replySent: "जवाब भेज दिया गया।",
      replySendFailed: "जवाब भेजा नहीं जा सका।",
      replyLoadFailed: "जवाब लोड नहीं हो सके।",
      replyDeleteNeedsSession: "जवाब हटाने के लिए सक्रिय लॉग-इन सेशन चाहिए।",
      replyDeleteFailed: "जवाब हटाया नहीं जा सका।",
      inboxLoadFailed: "फ़ीडबैक सूची लोड नहीं हो सकी।",
    },
  },
};

export function getSettingsCopy(outputLanguage = "ko") {
  return SETTINGS_COPY[outputLanguage] ?? SETTINGS_COPY.ko;
}

export function getSettingsDateLocale(outputLanguage = "ko") {
  return getSettingsCopy(outputLanguage).locale;
}

export function getSettingsLanguageOptions() {
  return OUTPUT_LANGUAGE_OPTIONS;
}
