const UI_COPY = {
  ko: {
    planNames: {
      free: "무료",
      pro: "프로",
      premium: "프리미엄",
    },
    header: {
      homeAria: "홈으로 이동",
      refresh: "새로고침",
      refreshing: "동기화 중...",
      billing: "요금제",
      settings: "설정",
      sharedSpace: "공유 스페이스",
      personalSpace: "개인 스페이스",
      pinChange: "PIN 변경",
      login: "로그인",
    },
    upload: {
      limitText: (tierLabel, sizeLabel) => `${tierLabel} 요금제: 파일 1개당 최대 ${sizeLabel}`,
      folderFeatureLocked: "폴더 기능은 Pro/Premium에서 제공됩니다.",
      addDocument: "문서 추가",
      uploadPrompt: "PDF, DOCX, PPTX 파일을 업로드하세요",
      previewPdfOnly: "미리보기는 PDF만 지원됩니다",
      createFolder: "폴더 생성",
      noFiles: "파일이 없습니다.",
      noFilesInFolder: "이 폴더에 파일이 없습니다.",
      folderLabel: "폴더",
      filesCount: (count) => `${count}개 파일`,
      addNewFileHere: "여기에 새 파일 추가",
      folderRenameTitle: "폴더 이름 변경",
      folderCreateTitle: "폴더 만들기",
      folderRenameDescription: "새 폴더 이름을 입력해 주세요.",
      folderCreateDescription: "폴더 이름을 입력해 주세요.",
      folderRenameSubmit: "변경",
      folderCreateSubmit: "생성",
      folderPlaceholder: "예: 1주차 강의, 중간고사 요약",
      cancel: "취소",
      closeFolderAria: "폴더 닫기",
      rename: "이름 변경",
      addDocumentToFolder: "폴더에 문서 추가",
      close: "닫기",
      addFileToFolder: "이 폴더에 파일 추가",
      emptyFolderDescription: "아직 문서가 없습니다. PDF, DOCX, PPTX 파일을 바로 업로드하세요.",
      folderSummaryName: (folderName) => `${folderName} 전체 요약본`,
      folderSummaryMeta: (count) => `${count}개 파일 요약 기반`,
      moveOutOfFolder: "폴더 밖으로 이동",
      noFolders: "폴더가 없습니다.",
    },
  },
  en: {
    planNames: {
      free: "Free",
      pro: "Pro",
      premium: "Premium",
    },
    header: {
      homeAria: "Go home",
      refresh: "Refresh",
      refreshing: "Syncing...",
      billing: "Pricing",
      settings: "Settings",
      sharedSpace: "Shared Space",
      personalSpace: "Personal Space",
      pinChange: "Change PIN",
      login: "Log In",
    },
    upload: {
      limitText: (tierLabel, sizeLabel) => `${tierLabel} plan: up to ${sizeLabel} per file`,
      folderFeatureLocked: "Folders are available on Pro and Premium.",
      addDocument: "Add Document",
      uploadPrompt: "Upload PDF, DOCX, or PPTX files",
      previewPdfOnly: "Preview is available for PDF only",
      createFolder: "Create Folder",
      noFiles: "No files yet.",
      noFilesInFolder: "This folder is empty.",
      folderLabel: "Folder",
      filesCount: (count) => `${count} file${count === 1 ? "" : "s"}`,
      addNewFileHere: "Add a new file here",
      folderRenameTitle: "Rename Folder",
      folderCreateTitle: "Create Folder",
      folderRenameDescription: "Enter a new folder name.",
      folderCreateDescription: "Enter a folder name.",
      folderRenameSubmit: "Rename",
      folderCreateSubmit: "Create",
      folderPlaceholder: "e.g. Week 1 Lecture, Midterm Notes",
      cancel: "Cancel",
      closeFolderAria: "Close folder",
      rename: "Rename",
      addDocumentToFolder: "Add document to folder",
      close: "Close",
      addFileToFolder: "Add files to this folder",
      emptyFolderDescription: "No documents yet. Upload PDF, DOCX, or PPTX files right away.",
      folderSummaryName: (folderName) => `${folderName} combined summary`,
      folderSummaryMeta: (count) => `Based on ${count} file${count === 1 ? "" : "s"}`,
      moveOutOfFolder: "Move out of folder",
      noFolders: "No folders available.",
    },
  },
  zh: {
    planNames: {
      free: "免费",
      pro: "Pro",
      premium: "Premium",
    },
    header: {
      homeAria: "返回首页",
      refresh: "刷新",
      refreshing: "同步中...",
      billing: "价格",
      settings: "设置",
      sharedSpace: "共享空间",
      personalSpace: "个人空间",
      pinChange: "修改 PIN",
      login: "登录",
    },
    upload: {
      limitText: (tierLabel, sizeLabel) => `${tierLabel} 方案: 单个文件最大 ${sizeLabel}`,
      folderFeatureLocked: "文件夹功能仅在 Pro / Premium 提供。",
      addDocument: "添加文档",
      uploadPrompt: "上传 PDF、DOCX、PPTX 文件",
      previewPdfOnly: "仅支持 PDF 预览",
      createFolder: "创建文件夹",
      noFiles: "暂无文件。",
      noFilesInFolder: "此文件夹中暂无文件。",
      folderLabel: "Folder",
      filesCount: (count) => `${count} 个文件`,
      addNewFileHere: "在这里添加新文件",
      folderRenameTitle: "修改文件夹名称",
      folderCreateTitle: "创建文件夹",
      folderRenameDescription: "请输入新的文件夹名称。",
      folderCreateDescription: "请输入文件夹名称。",
      folderRenameSubmit: "修改",
      folderCreateSubmit: "创建",
      folderPlaceholder: "例如：第1周讲义、期中考试总结",
      cancel: "取消",
      closeFolderAria: "关闭文件夹",
      rename: "修改名称",
      addDocumentToFolder: "向文件夹添加文档",
      close: "关闭",
      addFileToFolder: "向此文件夹添加文件",
      emptyFolderDescription: "还没有文档。现在就上传 PDF、DOCX、PPTX 文件。",
      folderSummaryName: (folderName) => `${folderName} 合并摘要`,
      folderSummaryMeta: (count) => `基于 ${count} 个文件摘要`,
      moveOutOfFolder: "移出文件夹",
      noFolders: "没有可用文件夹。",
    },
  },
  ja: {
    planNames: {
      free: "無料",
      pro: "Pro",
      premium: "Premium",
    },
    header: {
      homeAria: "ホームへ移動",
      refresh: "更新",
      refreshing: "同期中...",
      billing: "料金",
      settings: "設定",
      sharedSpace: "共有スペース",
      personalSpace: "個人スペース",
      pinChange: "PIN変更",
      login: "ログイン",
    },
    upload: {
      limitText: (tierLabel, sizeLabel) => `${tierLabel}プラン: 1ファイルあたり最大${sizeLabel}`,
      folderFeatureLocked: "フォルダ機能は Pro / Premium で利用できます。",
      addDocument: "文書を追加",
      uploadPrompt: "PDF、DOCX、PPTXファイルをアップロードしてください",
      previewPdfOnly: "プレビューはPDFのみ対応しています",
      createFolder: "フォルダ作成",
      noFiles: "ファイルがありません。",
      noFilesInFolder: "このフォルダにはファイルがありません。",
      folderLabel: "Folder",
      filesCount: (count) => `${count}件のファイル`,
      addNewFileHere: "ここに新しいファイルを追加",
      folderRenameTitle: "フォルダ名を変更",
      folderCreateTitle: "フォルダを作成",
      folderRenameDescription: "新しいフォルダ名を入力してください。",
      folderCreateDescription: "フォルダ名を入力してください。",
      folderRenameSubmit: "変更",
      folderCreateSubmit: "作成",
      folderPlaceholder: "例: 第1週講義、中間試験まとめ",
      cancel: "キャンセル",
      closeFolderAria: "フォルダを閉じる",
      rename: "名前変更",
      addDocumentToFolder: "フォルダに文書を追加",
      close: "閉じる",
      addFileToFolder: "このフォルダにファイルを追加",
      emptyFolderDescription: "まだ文書がありません。PDF、DOCX、PPTXファイルをすぐアップロードしてください。",
      folderSummaryName: (folderName) => `${folderName} 統合要約`,
      folderSummaryMeta: (count) => `${count}件のファイル要約ベース`,
      moveOutOfFolder: "フォルダの外へ移動",
      noFolders: "フォルダがありません。",
    },
  },
  hi: {
    planNames: {
      free: "मुफ़्त",
      pro: "Pro",
      premium: "Premium",
    },
    header: {
      homeAria: "होम पर जाएँ",
      refresh: "रीफ़्रेश",
      refreshing: "सिंक हो रहा है...",
      billing: "प्लान",
      settings: "सेटिंग्स",
      sharedSpace: "शेयर्ड स्पेस",
      personalSpace: "पर्सनल स्पेस",
      pinChange: "PIN बदलें",
      login: "लॉग इन",
    },
    upload: {
      limitText: (tierLabel, sizeLabel) => `${tierLabel} प्लान: प्रति फ़ाइल अधिकतम ${sizeLabel}`,
      folderFeatureLocked: "फ़ोल्डर फीचर केवल Pro / Premium में उपलब्ध है।",
      addDocument: "दस्तावेज़ जोड़ें",
      uploadPrompt: "PDF, DOCX, PPTX फ़ाइलें अपलोड करें",
      previewPdfOnly: "प्रीव्यू केवल PDF के लिए उपलब्ध है",
      createFolder: "फ़ोल्डर बनाएँ",
      noFiles: "अभी कोई फ़ाइल नहीं है।",
      noFilesInFolder: "इस फ़ोल्डर में कोई फ़ाइल नहीं है।",
      folderLabel: "फ़ोल्डर",
      filesCount: (count) => `${count} फ़ाइल`,
      addNewFileHere: "यहाँ नई फ़ाइल जोड़ें",
      folderRenameTitle: "फ़ोल्डर का नाम बदलें",
      folderCreateTitle: "फ़ोल्डर बनाएँ",
      folderRenameDescription: "नया फ़ोल्डर नाम दर्ज करें।",
      folderCreateDescription: "फ़ोल्डर का नाम दर्ज करें।",
      folderRenameSubmit: "बदलें",
      folderCreateSubmit: "बनाएँ",
      folderPlaceholder: "उदाहरण: सप्ताह 1 लेक्चर, मिडटर्म नोट्स",
      cancel: "रद्द करें",
      closeFolderAria: "फ़ोल्डर बंद करें",
      rename: "नाम बदलें",
      addDocumentToFolder: "फ़ोल्डर में दस्तावेज़ जोड़ें",
      close: "बंद करें",
      addFileToFolder: "इस फ़ोल्डर में फ़ाइल जोड़ें",
      emptyFolderDescription: "अभी कोई दस्तावेज़ नहीं है। अभी PDF, DOCX, PPTX फ़ाइलें अपलोड करें।",
      folderSummaryName: (folderName) => `${folderName} संयुक्त सारांश`,
      folderSummaryMeta: (count) => `${count} फ़ाइलों के सारांश पर आधारित`,
      moveOutOfFolder: "फ़ोल्डर से बाहर ले जाएँ",
      noFolders: "कोई फ़ोल्डर नहीं है।",
    },
  },
};

export function getUiCopy(outputLanguage = "ko") {
  return UI_COPY[outputLanguage] ?? UI_COPY.ko;
}
